### ISSUE TITLE
Error generating signed APK: TypeError: Cannot read property 'writeFile' of undefined [BUG]

### ISSUE THREAD

**Issue by gregpm** [pwa-builder/CloudAPK#17]
I am getting an error page when trying to generate / download the Android APK. I have tried a couple of different PWA sites but still get the same error. Thank you in advance.

**Comment by JudahGabriel** [comment]
We're aware of this and it's being fixed now. We should have an updated either today or tomorrow with the fix. I'll comment here when it's ready.

**Comment by jgw96** [comment]
Hello all! This is now fixed 🎉 and tested and has been deployed to prod. Because of this, I am going to close this issue but if you all run into this problem again please feel free to comment and ill re-open and take another look!

**Comment by gregpm** [comment]
Awesome, thanks very much Justin and Judah!

**Comment by jgw96** [comment]
No problem at all!
