### ISSUE TITLE
Building android app generates inernal server error

### ISSUE THREAD

**Issue by amanintech** [pwa-builder/CloudAPK#20]
After adding the URL and finally clicking on download generates an internal server error
![image](https://user-images.githubusercontent.com/28403318/80915780-1ff29080-8d72-11ea-8cca-f265eeae7770.png)

**Comment by andreban** [comment]
I can repro that. Here's the error message I get from the request:
```
Invalid PWA settings: name is required
```

Here's way the payload sent to `generateSignedApkZip` looks like:
```
{
    "packageId": "com..twa",
    "host": "pwa-directory.appspot.com",
    "name": "",
    "themeColor": "transparent",
    "navigationColor": "transparent",
    "backgroundColor": "transparent",
    "startUrl": "/manifest.json",
    "iconUrl": "https://pwa-directory.appspot.com/favicon.ico",
    "maskableIconUrl": null,
    "appVersion": "1.0.0",
    "useBrowserOnChromeOS": true,
    "splashScreenFadeOutDuration": 300,
    "enableNotifications": false,
    "shortcuts": [],
    "signingInfo": {
        "fullName": "John Doe",
        "organization": "Contoso",
        "organizationalUnit": "Engineering Department",
        "countryCode": "US"
    }
}
```

Another point is that the generated packageId is also invalid: `com..twa`.

**Comment by JudahGabriel** [comment]
Woops, looks like something broke on our deploy. We should have a fix for you Monday or Tuesday.

**Comment by jgw96** [comment]
Hello all! Looks like our service went down over the weekend, i am looking into things now and will respond when fixed (:

**Comment by jgw96** [comment]
Hey all! The service is now back up and running, sorry for the issues! Since the service is back up I am going to close this for now but @JudahGabriel , on Tuesday lets talk about what i found and we can open an issue to fix the deeper cause.

**Comment by amanintech** [comment]
It still returns error 
![image](https://user-images.githubusercontent.com/28403318/80970229-71fde980-8e38-11ea-95d3-89fd3bb373d1.png)

**Comment by JudahGabriel** [comment]
@amanintech working on this end - I'm successfully generating an APK. Can I ask what URL you're using?

**Comment by amanintech** [comment]
It doesn't work reliably. Sometimes it does sometimes it doesn't. I am trying to retrace the network call and more information about the error.

Also, I think the styling part doesn't generate the right manifest file.

eg. I chose the standalone display view of the PWA but still, the generated app had it with the address bar. Is it supposed to be like that? 
or should I raise a separate issue explaining the error?

**Comment by JudahGabriel** [comment]
Let me know if there's a failing URL.

Address bar on Android: Did you generate the digital asset links? When you generate an APK, we include a "Next steps" readme file that describes how to do this. Chrome on Android requires you have a digital assets link file to verify ownership of the PWA domain. Once you have that, address bar will disappear.
