### ISSUE TITLE
Output App Bundles instead of APKs

### ISSUE THREAD

**Issue by knurillaev** [pwa-builder/CloudAPK#23]
what to do problems with downloading an unrecognized APK file to google play
Warning

This APK file contains unused resources and code that end up with users. You can reduce the size of the app using the Android App Bundle. Because you haven't optimized the app for different device configurations, users have to download and install more data. Large apps take up a lot of space on your devices, and users install them less frequently.

Decision

Use the Android App Bundle to automatically optimize the app for different device configurations, or manage optimization yourself with multiple APK files.

**Comment by andreban** [comment]
Hi @knurillaev,

This is related to this Bubblewrap issue: https://github.com/GoogleChromeLabs/bubblewrap/issues/119

AppBundles helps breaking App content into smaller packages and ensures that only what is needed on each device is downloaded. But the generated project is already minimal and it's unlikely that App Bundles will generate benefits for apps generated via Bubblewrap / PWABuilder.

Nevertheless, we plan on outputting App Bundles to help avoiding the Play Store warning.

**Comment by andreban** [comment]
@jgw96 @knurillaev it might be worth changing the name of the issue to "Output App Bundles insteads of APKs" or something similar.

**Comment by JudahGabriel** [comment]
Sounds good. @andreban let us know when bubblewrap supports App Bundles, we'll do any necessary updates on our end.

**Comment by knurillaev** [comment]
how can I transform if the pwabuilder site doesn't provide the source code for performing the actions you said

**Comment by mthlongwane** [comment]
Hi I am also stuck here and am unable to release the beta version of my app. Was anyone able to solve it? Would really appreciate any help!
![image](https://user-images.githubusercontent.com/33334535/87479049-1071ac80-c62b-11ea-8f56-e25ce2cc3d1d.png)

**Comment by JudahGabriel** [comment]
@mthlongwane You can dismiss that error; **your PWA app will still be published**. The Bubblewrap team hasn't migrated to App Bundles yet, so this warning comes with the territory for now.

**Comment by andreban** [comment]
We have introduced support for App Bundles on Bubblewrap 1.5.0 ([changelog](https://github.com/GoogleChromeLabs/bubblewrap/releases/tag/v1.5.0)). 

This is how the Bubblewrap CLI uses it:
```typescript
  async buildAppBundle(signingKey: SigningKeyInfo, passwords: SigningKeyPasswords): Promise<void> {
    await this.gradleWrapper.bundleRelease();
    const inputFile = 'app/build/outputs/bundle/release/app-release.aab';
    const outputFile = './app-release-bundle.aab';
    await this.jarSigner.sign(
        signingKey, passwords.keystorePassword, passwords.keyPassword, inputFile, outputFile);
    this.prompt.printMessage(messages.messageAppBundleSuccess(outputFile));
  }
```

**Comment by JudahGabriel** [comment]
Thanks, @andreban. Do these .aab files work just like .apk files - can I open them on an Android device to install them, or drag and drop an .aab file on an Android emulator to install it?

**Comment by andreban** [comment]
They don't - you'd have to use bundletool to transform into an APK: https://developer.android.com/studio/command-line/bundletool

What we're doing in the Bubblewrap CLI is to build both formats - APK can be side-loaded to the phone (and installed via `bubblewrap install` while the .aab can be uploaded to Play.

**Comment by JudahGabriel** [comment]
Thanks. I'll talk to the team about generating both the APK and the .aab files.

**Comment by santiq** [comment]
I'm facing the same issue as @mthlongwane 
I dismissed the warning, but my app is not publishing

**Comment by andreban** [comment]
@santiq approval may take a while. What the Play Store shows is just a warning and won't block publishing.

**Comment by santiq** [comment]
@andreban Nope, I can't click the publish button.

This is an internal release for testing btw

![Screen Shot 2020-07-27 at 18 42 19](https://user-images.githubusercontent.com/7070683/88595377-350d5180-d039-11ea-860a-3d26632372d9.png)

**Comment by andreban** [comment]
@santiq what does the warning message under "View warning message" say?

**Comment by santiq** [comment]
@andreban Same as @mthlongwane 

![Screen Shot 2020-07-28 at 11 54 21](https://user-images.githubusercontent.com/7070683/88682774-751c1500-d0c9-11ea-8d62-f33791734512.png)

**Comment by Conmariin** [comment]
Same here. Obviously it's not an option anymore! After closing this message the Publish-Button is still greyed out. AAB seems to be mandatory.

**Comment by santiq** [comment]
@Conmariin check this out https://stackoverflow.com/questions/42925447/start-rollout-to-beta-disabled-in-play-store-developer-console

**Comment by Conmariin** [comment]
@santiq Thanks! That was it! Everything works also fine with normal APK's. My fault!

**Comment by JudahGabriel** [comment]
Implemented. We now generate both .apk (for testing) and .aab (for submitting to Store). We've [updated our documentation](https://github.com/pwa-builder/CloudAPK/blob/master/Next-steps.md#3-upload-your-app-to-the-google-play-store) accordingly.
