### ISSUE TITLE
[Question] Generate APK Unsigned does not install

### ISSUE THREAD

**Issue by maccali** [pwa-builder/CloudAPK#29]
The Generate APK Unsigned does not install

When he installs it says "The app was not installed" how to proceed?

**Comment by JudahGabriel** [comment]
@maccali Yeah, unsigned packages can't be installed. To test your APK, generate a signed package instead.

You can do that in the PWABuilder Android options:

![image](https://user-images.githubusercontent.com/312936/87729579-905a5c80-c77a-11ea-9ddf-a02abe52929c.png)

![image](https://user-images.githubusercontent.com/312936/87729906-49b93200-c77b-11ea-8348-87b00363bac7.png)

FYI, we're updating PWABuilder to generating a signed package by default. In the meantime, though, go ahead and create a signed package as shown above.
