### ISSUE TITLE
Building APK failing for qrsnapper.com

### ISSUE THREAD

**Issue by andreban** [pwa-builder/CloudAPK#3]
When trying to build for https://qrsnapper.com, web server crashes. It seems the issue is that Android doesn't like the package name being generated for the app: 

```
error: attribute 'package' in tag is not a valid Android package name: 'com.myapp.Snap QR'.
```

One alternative is to use reverse the domain name for the app and append ".twa" to the end. For qrsnapper, the package-name becomes `com.qrsnapper.twa`.

More details on Android practices and restrictions for the application-ids are here: https://developer.android.com/studio/build/application-id

**Comment by JudahGabriel** [comment]
Thanks. The problem was with our package ID generation. @jgw96 fixed this and we've deployed the fix to production.
