### ISSUE TITLE
Website Update but App didn't, Why?

### ISSUE THREAD

**Issue by fidox89** [pwa-builder/CloudAPK#30]
Hi, i'm testing my apk, it works fine, but I added some stuff to my website, but it doesn't show in app. why?

**Comment by JudahGabriel** [comment]
Almost certainly, your web app is serving an old cached version. 

Do you have a service worker? What's its caching policy?

**Comment by JudahGabriel** [comment]
@fidox89 bump

**Comment by JudahGabriel** [comment]
Haven't heard from you. Closing.
