### ISSUE TITLE
Play Store App signing key available on Play Console

### ISSUE THREAD

**Issue by valentinoli** [pwa-builder/CloudAPK#49]
I found out the key that Play Store uses to sign the app can be found on Play Console ([as also explained here](https://developers.google.com/web/android/trusted-web-activity/quick-start#play-store-signing)) by following these steps:

1. Selecting your app
2. Setup --> App signing
3. App signing key certificate --> "SHA-256 certificate fingerprint"

The [instructions for removing the browser address bar](https://github.com/pwa-builder/CloudAPK/blob/master/Asset-links.md#validate-your-assetlinksjson-file) explain how the same can be achieved using the Asset Links Tool app. I suggest updating the instructions with this alternative as I can imagine many developers find this more convenient, especially if they don't have an Android phone (granted they have authorized access to this section of the Play Console).

**Comment by JudahGabriel** [comment]
Thanks. We've updated the asset links explainer and the next steps explainer. 👍
