### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by aouniradouan** [pwa-builder/CloudAPK#50]
**Question in detail**
Hello,
I have 3 PWA in one application and i want to upload them to Play Store but just one app it showing correctly because of assetslink.json i have just one and the other app must have the same file but with different informations inside.
is there way to solve that please ?

**Comment by JudahGabriel** [comment]
@aouniradouan Your question is unclear. Are you saying that you have 2 Android apps that show the address bar?

**Comment by aouniradouan** [comment]
> @aouniradouan Your question is unclear. Are you saying that you have 2 Android apps that show the address bar?

No, i have a food Delivery application so i have one for delivery Guy and Customer and store owner apps all this apps is have one domaine and one hosting so how Can i remove the adresse bar in this applications please
I have already removed it from costumer app but the other i Can't

**Comment by JudahGabriel** [comment]
OK, I think this will work. You'll need multiple entries in your assetlinks.json, one for each app:

```json
[
	{
		"relation": ["delegate_permission/common.handle_all_urls"],
		"target": {
			"namespace": "android_app",
			"package_name": "com.deliveryapp.deliveryguy",
			"sha256_cert_fingerprints": ["fingerprint goes here"]
		}
	},

	{
		"relation": ["delegate_permission/common.handle_all_urls"],
		"target": {
			"namespace": "android_app",
			"package_name": "com.deliveryapp.customer",
			"sha256_cert_fingerprints": ["fingerprint goes here"]
		}
	},

	{
		"relation": ["delegate_permission/common.handle_all_urls"],
		"target": {
			"namespace": "android_app",
			"package_name": "com.deliveryapp.owner",
			"sha256_cert_fingerprints": ["fingerprint goes here"]
		}
	}
]
```

Obviously, fill in the correct "package_name" and "sha256_cert_fingerprints" for each app.

**Comment by aouniradouan** [comment]
> OK, I think this will work. You'll need multiple entries in your assetlinks.json, one for each app:
> 
> ```json
> [
> 	{
> 		"relation": ["delegate_permission/common.handle_all_urls"],
> 		"target": {
> 			"namespace": "android_app",
> 			"package_name": "com.deliveryapp.deliveryguy",
> 			"sha256_cert_fingerprints": ["fingerprint goes here"]
> 		}
> 	},
> 
> 	{
> 		"relation": ["delegate_permission/common.handle_all_urls"],
> 		"target": {
> 			"namespace": "android_app",
> 			"package_name": "com.deliveryapp.customer",
> 			"sha256_cert_fingerprints": ["fingerprint goes here"]
> 		}
> 	},
> 
> 	{
> 		"relation": ["delegate_permission/common.handle_all_urls"],
> 		"target": {
> 			"namespace": "android_app",
> 			"package_name": "com.deliveryapp.owner",
> 			"sha256_cert_fingerprints": ["fingerprint goes here"]
> 		}
> 	}
> ]
> ```
> 
> Obviously, fill in the correct "package_name" and "sha256_cert_fingerprints" for each app.

Thank You ❤️ And Also is there any way to remove the translation bar in browser please ?

**Comment by davrous** [comment]
Hi, we can't control the browser behavior (such as extensions loaded) from a PWA/TWA. Closing the issue and the original question has been answered.
