### ISSUE TITLE
Intent-Filters

### ISSUE THREAD

**Issue by FrankVDL2471** [pwa-builder/CloudAPK#52]
Is it possible to add Intent-Filters to the generated android APK ?

When my PWA is opened directly in a WebBrowser, I want to have the option to move  to the native app. As it will have a beter (fullscreen) experience.

I looked into A2HS options for PWA but they are to user driven. 
Once a uses cancels the inital request to install the app, the question is not returned.
Also does not seem to be possible to jump "installed" version of the PWA neither.

**Comment by JudahGabriel** [comment]
Hi @FrankVDL2471 

Have you checked out [getInstalledRelatedApps()](https://web.dev/get-installed-related-apps/)? You may be able to switch to your native app entirely from web code.

If not, we do offer source code download. When packaging your app for Android on PWABuilder.com, choose `Options` - there will be an option for downloading the Android app source code. From there, you can do whatever you like.

p.s. I recommend you ask future questions in the main [PWABuilder repo](https://github.com/pwa-builder/pwabuilder/issues), which gets more eyes on it.

**Comment by davrous** [comment]
Closing as it's been followed there: https://github.com/pwa-builder/PWABuilder/issues/1317
