### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by canbax** [pwa-builder/CloudAPK#56]
**Describe the bug**
Probably this bug is specifically related to Github-pages but anyway let me show you.

/.well-known/assetlinks.json is not served through Github-pages

**To Reproduce**
You can see that my file is here in the right folder. https://github.com/canbax/namaz-vakti/tree/gh-pages/.well-known
but if you go and open https://canbax.github.io/namaz-vakti/.well-known/assetlinks.json you see 404. My project is actively deployed here https://canbax.github.io/namaz-vakti/

When I put my file to the root, not in the _".well-known"_ folder it was visible but now it is not.

**Comment by davrous** [comment]
Hi @canbax, sorry for the delay in our answer. As you say, this is github related issue. But maybe @JudahGabriel knows how to workaround this.

**Comment by andreban** [comment]
I wonder if this workaround helps: https://developers.google.com/web/android/trusted-web-activity/quick-start#jekyll_based_websites

**Comment by canbax** [comment]
Thank you! The file is now served. You are very helpful.
