### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by allan-simon** [pwa-builder/CloudAPK#60]
**Question in detail**

Once I've downloaded the zip with the source checkbox check,  I guess I have everything to compile the app myself, if so which command do i need ? (i'm quite new to app development, and your website really help me to jump the gap )

**Comment by JudahGabriel** [comment]
Hi @allan-simon 

The source is a standard Android project that can be opened in Android Studio. Again, you should only do that if you're customizing the Android package beyond what pwabuilder.com allows.

p.s. please open future issues on our [main repo](https://github.com/pwa-builder/pwabuilder/issues).

**Comment by allan-simon** [comment]
I was more thinking about integrating it in a CI/CD process once the initial generation from pwabuilder , but if it's a standard android app, then I will check in that direction :)
