### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dvijeniii05** [pwa-builder/CloudAPK#64]
**Describe the bug**
Hi there. 
I used pwa builder to build app for Google Play. All worked fine, no issues. Uploaded .aab to the store, it is approved and downloadable. 

However now i would like to change splash screen. But when i go to PWAbuilder to make an update on version, after i add my url to analyse it takes ages to analyse the left bar ( about 20 minutes) and then fails them. 

**To Reproduce**
Go to following link: https://www.pwabuilder.com/

Then implement my url: clicktoplay.ru/

And it just doesnt analyse it correctly.

Any advice will be appreciated.

**Comment by JudahGabriel** [comment]
We had an issue with our API over the weekend. It was resolved Monday morning. I just tested your URL, and it's working fine.

FYI, in the future, I recommend opening issues on our [main repo](https://github.com/pwa-builder/pwabuilder/issues).
