### ISSUE TITLE
Always getting response of twaManifest.shortcuts.map is not a function

### ISSUE THREAD

**Issue by ajeetku** [pwa-builder/CloudAPK#7]
twaManifest.shortcuts.map is not a function

**Comment by andreban** [comment]
I suspect this is related to this llama-pack change: https://github.com/GoogleChromeLabs/llama-pack/pull/99

`twaManifest.shortcuts` used to be of type `string`, but has been replaced with `ShortcutInfo[]`, to make it more structured and safer to use across the code.

**Comment by JudahGabriel** [comment]
We'll have a fix for this shortly as we migrate from llama-pack to bubblewrap.

**Comment by JudahGabriel** [comment]
This has been fixed from the CloudAPK side for awhile. However, PWABuilder website still would pass a string here. This has been fixed [here](https://github.com/pwa-builder/PWABuilder/pull/698).
