### ISSUE TITLE
Deployed assetlinks.json, but bar still shows

### ISSUE THREAD

**Issue by rotem-hen** [pwa-builder/CloudAPK#73]
I deployed the provided json file (this path is accessible: https://ricette.co.il/.well-known/assetlinks.json).
Then I tested the provided APK and installed it on my device - but I see the url bar shows.
How can I fix this?

**Comment by rotem-hen** [comment]
Used a different service, thanks

**Comment by jadamec** [comment]
> Used a different service, thanks

Hi, which service did you used please? I've a same issue now.

**Comment by jadamec** [comment]
Yeah, [Clearing the site's cache](https://github.com/pwa-builder/CloudAPK/blob/master/Asset-links.md#clearing-your-sites-cache) worked for me! :)

**Comment by rotem-hen** [comment]
> Hi, which service did you use please? I've a same issue now.
 It's called PWA2APK, but I don't recommend them, they don't have any kind of support.

**Comment by JudahGabriel** [comment]
For what it's worth, any platform that uses the Android Trusted Web Activity (TWA) platform will have this potential issue. 

To fix it, you need to follow the steps described in our [Asset Links explainer](https://github.com/pwa-builder/CloudAPK/blob/master/Asset-links.md).

**Comment by rotem-hen** [comment]
> For what it's worth, any platform that uses the Android Trusted Web Activity (TWA) platform will have this potential issue.
> 
> To fix it and remove the address bar, you need to follow the steps described in our [Asset Links explainer](https://github.com/pwa-builder/CloudAPK/blob/master/Asset-links.md).

Thank you for that! apparently I had a redirect from www.mysite.com to mysite.com, and I used www when generating the APK. I don't think I could solve this without your guide. Thanks again.
