### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by kishanbharda** [pwa-builder/CloudAPK#85]
I have successfully generated my PWA android app package. Now as a further step, I have to upload `assetlinks.json` to my server's root folder to remove the address bar in the app. But what if I don't have access to the root folder? My site is built on Shopify. Shopify does not allow us to upload any file to its root, we have to upload it through its file settings or in assets, which will serve using CDN. So I don't have options to upload files that can be accessed through the URL like `https://www.site.com/.well-known/assetlinks.json`.

So, Is there any solution for this issue?

**Comment by JudahGabriel** [comment]
Hi @kishanbharda 

Good question. I recommend you ask this question over at the [Google Bubblewrap repo](https://github.com/googlechromelabs/bubblewrap/issues), which is what PWABuilder uses internally.
